# Generated by Django 4.2.16 on 2024-11-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations',
            options={'ordering': ['-date_and_time']},
        ),
        migrations.AddField(
            model_name='reservations',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
