# Generated by Django 4.2.16 on 2024-11-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_reservations_options_reservations_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='name',
            field=models.CharField(default='hello'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='name_2',
            field=models.CharField(null=True),
        ),
    ]
