# Generated by Django 4.2.16 on 2024-11-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_reservations_name_reservations_name_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='name',
            field=models.CharField(),
        ),
    ]
